### ISSUE TITLE
Demonstrate utility of kerchunked data

### ISSUE THREAD

**Issue by maxrjones** [ProjectPythia/kerchunk-cookbook#16]
As suggested by @martindurant  in https://github.com/ProjectPythia/kerchunk-cookbook/pull/15#issue-1578630547, the visualizations at the end of the could be expanded to better demonstrate the utility of kerchunked data relative to using the original archival file format.

@jbednar also mentioned improved visualizations for Pangeo-ML notebooks. A great way to improve the visualizations and demonstrate the utility of kerchunk would be to add a tool for exploring changes through time of the kerchunked datasets, similar to the example in the [geoviews homepage](https://geoviews.org/), along with some narrative.

Any follow-up thoughts, @martindurant @jbednar or @norlandrhagen?

**Comment by martindurant** [comment]
I didn't specifically mean "visuals" in the sense of hvPlot et al (although those are certainly very nice), but simple tables of benchmarks or different cuts of the aggregate dataset that could not easily be done with xarray acting on netCDFs alone. For real interactive viz, you normally also have to think about execution environment - so similar to other holoviz problems.

**Comment by maxrjones** [comment]
metrics are available in https://carbonplan.org/blog/kerchunk-climate-data
