### ISSUE TITLE
Provide context for the timing section of the dask chapter

### ISSUE THREAD

**Issue by maxrjones** [ProjectPythia/kerchunk-cookbook#27]
The new [kerchunk and dask](https://projectpythia.org/kerchunk-cookbook/notebooks/foundations/kerchunk_dask.html) chapter is excellent, nice work @norlandrhagen! My one recommendation is to provide a bit more context on the timings section. More specifically, I recommend running the original and dask version on the 2i2c-configured Jupyter Hub and providing a description of the specific instance used (CPU, RAM) and the location of the compute and data. I also recommend providing the total time rather than per-file time in the comparison table to reflect the fact that the total time includes more than just per-file processing (as explained in the full text)

**Comment by norlandrhagen** [comment]
https://github.com/ProjectPythia/kerchunk-cookbook/pull/29
