### ISSUE TITLE
Build is failing with a "NoCredentialsError"

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/kerchunk-cookbook#61]
The nightly builds for this cookbook have been failing for a while now.

The [latest build log](https://github.com/ProjectPythia/kerchunk-cookbook/actions/runs/9183845471/job/25255202003#step:20:97) shows a `NoCredentialsError` in the notebook `Parquet_Reference_Storage.ipynb`.

The same notebook runs without error interactively in the Pythia binder, so I'm not sure what's going on. But will try switching the nightly build to the binder instead of GitHub Actions.

**Comment by maxrjones** [comment]
Builds are passing again after https://github.com/ProjectPythia/kerchunk-cookbook/pull/70
