### ISSUE TITLE
Nightly builds failing for the last month

### ISSUE THREAD

**Issue by erogluorhan** [ProjectPythia/kerchunk-cookbook#66]
**What happened**:

Dear authors and/or contributors (cc'ing @norlandrhagen and @maxrjones as you have the two largest contributions), the nightly builds of this cookbook have been failing for about the last month. It seems like a dependency (ModuleNotFoundError) issue.

Could you please have a look at it?

Also, there had been an authentication issue mentioned in #61 but it seems to have been fixed now. You may want to make sure about it as well.

**Minimal Complete Verifiable Example**:

[Latest nightly build](https://github.com/ProjectPythia/kerchunk-cookbook/actions/runs/11376828484/job/31649941944) as of the creation of this issue.

**Anything else we need to know?**:

If you think it is due to Pythia infrastructure or something else other than the cookbook itself, please let us know.

**Comment by maxrjones** [comment]
Builds are passing again after https://github.com/ProjectPythia/kerchunk-cookbook/pull/70

**Comment by erogluorhan** [comment]
Thanks!
