### ISSUE TITLE
Consider removing Pangeo-Forge notebook

### ISSUE THREAD

**Issue by maxrjones** [ProjectPythia/kerchunk-cookbook#68]
The Pangeo-Forge kerchunk integration was a major step forward at the time to abstract away some of the complexities with Kerchunk. However, now that we have VirtualiZarr which allows users to leverage familiar Xarray syntax, I think Pangeo-Forge may actually add complexity rather than simplifying workflows. VirtualiZarr also seems to work well with Dask, whereas Pangeo-Forge is sometimes difficult to get working (e.g., the Pangeo Forge notebook is currently failing and the release timelines are causing issues with the CI #67). I'm wondering if we should remove that notebook from the cookbook. @norlandrhagen do you have thoughts about this suggestion?

**Comment by norlandrhagen** [comment]
Totally agree, cut cut cut!
