### ISSUE TITLE
About section edit access

### ISSUE THREAD

**Issue by norlandrhagen** [ProjectPythia/kerchunk-cookbook#7]
Hi there @mgrover1 or @ktyle or @brian-rose, I misspelled `Pythia` in the About section of this repo. I don't seem to have the right credentials to change this. Any chance someone with higher level permissions can update `Pithia` -> `Pythia`?

Thanks!

**Comment by mgrover1** [comment]
@norlandrhagen can you try again? You should be an admin

**Comment by norlandrhagen** [comment]
Thanks @mgrover1! All is fixed.
